### ISSUE TITLE
支持 qq 帐号登录

### ISSUE THREAD

**Issue by xiaohulu** [blocklang/blocklang.com#14]

**Comment by leinue** [comment]
不如使用 authing.cn 吧

**Comment by xiaohulu** [comment]
@leinue 我了解下 authing.cn

**Comment by xiaohulu** [comment]
@leinue 后续可考虑将 authing.cn 中的身份认证云作为 BlockLang 中的一个集成组件。
BlockLang 中后续会考虑引入组件商店，允许第三方组件开发商售卖组件。

**Comment by xiaohulu** [comment]
已支持
