### ISSUE TITLE
blocklang.com 好像访问不了？？？

### ISSUE THREAD

**Issue by edagarli** [blocklang/blocklang.com#432]
辞掉工作，勇气很赞。我也是干低代码开发平台的，有机会一起交流。 
ps: 好像不好留言，就发个issues了，晚点我关闭下。

**Comment by edagarli** [comment]
blocklang.com 好像访问不了？？？

**Comment by xiaohulu** [comment]
@edagarli 谢谢，很高兴收到您的留言。新版稳定后马上部署到 blocklang.com 上。
